controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    back_steer_position_controller:
      type: forward_command_controller/ForwardCommandController

    front_wheel_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    arm_hold_controller:
      type: forward_command_controller/ForwardCommandController


back_steer_position_controller:
  ros__parameters:
    joints:
      - back_left_steer_joint
      - back_right_steer_joint
    interface_name: position

front_wheel_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
    interface_name: velocity

arm_hold_controller:
  ros__parameters:
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - ee_slider_joint
    interface_name: position